# Generated by Django 4.1.2 on 2022-10-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_rename_mymodelname_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(choices=[('M', 'Makeup'), ('N', 'Nail service'), ('H', 'Hair service'), ('C', 'Cosmetology'), ('Ms', 'Massage')], help_text='Select type of service', max_length=30)),
                ('service_price', models.IntegerField(help_text='Enter yuor price')),
                ('service_duration', models.IntegerField(help_text='Enter service duration')),
                ('name_of_master', models.TextField(help_text='Enter the name of master', max_length=30)),
            ],
        ),
    ]
